### ISSUE TITLE
Support ARM64 (Multi arch)

### ISSUE THREAD

**Issue by jakobhviid** [jakobhviid/Zookeeper-Docker#5]
The image should support ARM64 and have a multi-architecture image.
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by jakobhviid** [comment]
Secrets have been added.

**Comment by dstoft** [comment]
This has been tested and works currently under the dockerhub tag "cfei/zookeeper:latest-multiarch". It was testing together with the Kafka image, in this issue: https://github.com/jakobhviid/Kafka-Docker/issues/6
I'm closing this issue now.
